# Generated by Django 2.1.15 on 2021-02-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_assistanceuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisements',
            name='image_adver',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen de anuncio'),
        ),
        migrations.AddField(
            model_name='advertisements',
            name='link_adver',
            field=models.URLField(blank=True, null=True, verbose_name='Links'),
        ),
        migrations.AlterField(
            model_name='advertisements',
            name='content',
            field=models.TextField(verbose_name='Anuncio'),
        ),
    ]
