# Generated by Django 2.1.15 on 2021-02-11 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckMediaUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.ContentMedia', verbose_name='Contenido')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.ContentHeader', verbose_name='Curso')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.Status', verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Check de modulo',
                'verbose_name_plural': 'Check de modulos',
            },
        ),
    ]
