# Generated by Django 2.1.15 on 2021-01-26 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkmediauser',
            name='content_media',
        ),
        migrations.RemoveField(
            model_name='checkmediauser',
            name='status',
        ),
        migrations.RemoveField(
            model_name='checkmediauser',
            name='user',
        ),
        migrations.DeleteModel(
            name='CheckMediaUser',
        ),
    ]
