# Generated by Django 2.1.15 on 2020-12-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LanguajeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languaje_name', models.CharField(max_length=254, verbose_name='Lenguaje')),
            ],
        ),
        migrations.CreateModel(
            name='StatesList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=254, verbose_name='Nombre de estado')),
            ],
        ),
    ]
