# Generated by Django 2.1.15 on 2020-12-04 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='languajelist',
            options={'verbose_name': 'Lenguaje', 'verbose_name_plural': 'Lenguajes'},
        ),
        migrations.AlterModelOptions(
            name='stateslist',
            options={'verbose_name': 'Estados', 'verbose_name_plural': 'Estados'},
        ),
    ]
