# Generated by Django 2.1.15 on 2020-12-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0002_auto_20201203_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Tipo de contenido')),
            ],
            options={
                'verbose_name': 'Tipo de contenido',
                'verbose_name_plural': 'Tipo de contenidos',
            },
        ),
    ]
