# Generated by Django 2.1.15 on 2021-01-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0003_contenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGrades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=254, verbose_name='Calificacion')),
            ],
            options={
                'verbose_name': 'Calificacion',
                'verbose_name_plural': 'Calificaciones',
            },
        ),
    ]
