# Generated by Django 2.1.15 on 2021-01-28 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0004_usergrades'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContentType',
        ),
    ]
