# Generated by Django 2.1.15 on 2021-02-11 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('status', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsUserTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Resp Usuario',
                'verbose_name_plural': 'Resp Usuarios',
            },
        ),
        migrations.CreateModel(
            name='AnswersTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=254, verbose_name='Respuesta')),
                ('is_correct', models.BooleanField(verbose_name='Correcta')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
            },
        ),
        migrations.CreateModel(
            name='ContentHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='', verbose_name='Imágen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='status.Status', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ContentMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Nombre de contenido')),
                ('description', models.TextField(blank=True, default='No hay descripción', null=True, verbose_name='Descripción')),
                ('notes', models.TextField(blank=True, default='No hay notas', null=True, verbose_name='Notas')),
                ('g_suite', models.CharField(blank=True, max_length=254, null=True, verbose_name='Documentos Google')),
                ('g_suite_slides', models.CharField(blank=True, max_length=254, null=True, verbose_name='Documentos Google')),
                ('g_suite_sheets', models.CharField(blank=True, max_length=254, null=True, verbose_name='Documentos Google')),
                ('video', models.URLField(blank=True, null=True, verbose_name='Video')),
                ('genially', models.URLField(blank=True, null=True, verbose_name='Link de Genially')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='', verbose_name='Seleccione documento PDF')),
                ('images', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Seleccione imágen')),
                ('activity_name', models.CharField(blank=True, max_length=254, null=True, verbose_name='Nombre de actividad')),
                ('activity_description', models.TextField(blank=True, null=True, verbose_name='Descripcion de actividad')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.ContentHeader', verbose_name='Nombre de curso')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='status.Status', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Contenido de curso',
                'verbose_name_plural': 'Contenido de cursos',
                'ordering': ['content'],
            },
        ),
        migrations.CreateModel(
            name='QuestionsTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=254, verbose_name='Pregunta')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.ContentHeader', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
            },
        ),
        migrations.CreateModel(
            name='SubscribeCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe_time', models.DateTimeField(auto_now_add=True, verbose_name='Solicitado')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.ContentHeader', verbose_name='Curso')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.StatusSubscribeCourse', verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'ordering': ['-subscribe_time'],
            },
        ),
        migrations.AddField(
            model_name='answerstest',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.QuestionsTest', verbose_name='Pregunta'),
        ),
        migrations.AddField(
            model_name='ansusertest',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.AnswersTest', verbose_name='Respuesta'),
        ),
        migrations.AddField(
            model_name='ansusertest',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.ContentHeader', verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='ansusertest',
            name='question',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses.QuestionsTest', verbose_name='Pregunta'),
        ),
        migrations.AddField(
            model_name='ansusertest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
