# Generated by Django 2.1.15 on 2020-12-04 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='', verbose_name='Imágen')),
                ('video', models.URLField(blank=True, null=True, verbose_name='Video')),
                ('multiimage', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Contenido multimedia')),
                ('multiimagetwo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Contenido multimedia')),
                ('notes', models.TextField(default='No hay notas aún', verbose_name='Notas')),
                ('advertisements', models.TextField(default='No hay anuncios aquí', verbose_name='Anuncios')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='status.Status', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['-created'],
            },
        ),
    ]
