# Generated by Django 3.1.3 on 2020-11-19 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['-created'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
    ]
