# Generated by Django 2.1.15 on 2020-12-29 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_contentheader_modulescourses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulescourses',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.ContentHeader', verbose_name='Contenido'),
        ),
    ]
