# Generated by Django 2.1.15 on 2020-12-29 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_contentcoursemedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribecourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.ContentHeader', verbose_name='Curso'),
        ),
    ]
