# Generated by Django 2.1.15 on 2021-01-15 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20210115_1542'),
        ('courses', '0006_auto_20201229_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='status',
        ),
        migrations.RemoveField(
            model_name='contentcoursemedia',
            name='content',
        ),
        migrations.RemoveField(
            model_name='contentcoursemedia',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='contentcoursemedia',
            name='module',
        ),
        migrations.RemoveField(
            model_name='contentcoursemedia',
            name='status',
        ),
        migrations.RemoveField(
            model_name='modulescourses',
            name='content',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='ContentCourseMedia',
        ),
        migrations.DeleteModel(
            name='ModulesCourses',
        ),
    ]
