# Generated by Django 2.1.15 on 2021-01-16 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20210116_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=254, verbose_name='Pregunta')),
                ('answer_v', models.CharField(max_length=254, verbose_name='Respuesta correcta')),
                ('answer_f1', models.CharField(max_length=254, verbose_name='Respuesta incorrecta')),
                ('answer_f2', models.CharField(max_length=254, verbose_name='Respuesta incorrecta')),
                ('answer_f3', models.CharField(max_length=254, verbose_name='Respuesta incorrecta')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.ContentHeader', verbose_name='Nombre de curso')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Examenes',
                'ordering': ['content'],
            },
        ),
    ]
