# Generated by Django 2.1.15 on 2021-01-28 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_contentmedia_genially'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmedia',
            name='g_suite_sheets',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Documentos Google'),
        ),
        migrations.AddField(
            model_name='contentmedia',
            name='g_suite_slides',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Documentos Google'),
        ),
    ]
