# Generated by Django 2.1.15 on 2021-01-29 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0013_auto_20210128_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsUserTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Resp Usuario',
                'verbose_name_plural': 'Resp Usuarios',
            },
        ),
        migrations.CreateModel(
            name='AnswersTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=254, verbose_name='Respuesta')),
                ('is_correct', models.BooleanField(verbose_name='Correcta')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
            },
        ),
        migrations.CreateModel(
            name='QuestionsTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=254, verbose_name='Pregunta')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.ContentHeader', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
            },
        ),
        migrations.AddField(
            model_name='answerstest',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.QuestionsTest', verbose_name='Pregunta'),
        ),
        migrations.AddField(
            model_name='ansusertest',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.AnswersTest', verbose_name='Respuesta'),
        ),
        migrations.AddField(
            model_name='ansusertest',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.ContentHeader', verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='ansusertest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
