# Generated by Django 2.1.15 on 2021-01-30 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20210129_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerTestCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_v', models.CharField(max_length=254, verbose_name='Respuesta correcta')),
                ('answer_f1', models.CharField(max_length=254, verbose_name='Respuesta falsa')),
                ('answer_f2', models.CharField(max_length=254, verbose_name='Respuesta falsa')),
                ('answer_f3', models.CharField(max_length=254, verbose_name='Respuesta falsa')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.QuestionsTest', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Respuesta v2',
                'verbose_name_plural': 'Respuestas v2',
            },
        ),
    ]
