# Generated by Django 2.1.15 on 2021-02-01 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20210129_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansusertest',
            name='question',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='courses.QuestionsTest', verbose_name='Pregunta'),
        ),
    ]
