# Generated by Django 2.1.15 on 2020-12-04 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('status', '0001_initial'),
        ('catalogues', '0001_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCertificates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.FileField(upload_to='', verbose_name='Certificado')),
                ('certificate_date', models.DateTimeField(verbose_name='Fecha de certificación')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Content', verbose_name='Curso')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.Status', verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Content', verbose_name='Nombre de curso')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.Status', verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nombre de usuario')),
            ],
            options={
                'verbose_name': 'Curso de usuario',
                'verbose_name_plural': 'Cursos de usuarios',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descripción del usuario')),
                ('user_image', models.ImageField(upload_to='', verbose_name='Imágen de usuario')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('certificates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.UserCertificates', verbose_name='Certificados')),
                ('languaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogues.LanguajeList', verbose_name='Lenguaje')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogues.StatesList', verbose_name='Estado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nombre de usuario')),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuarios',
            },
        ),
    ]
