# Generated by Django 3.1.3 on 2020-11-19 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('status', '0001_initial'),
        ('courses', '0002_auto_20201119_1138'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.content', verbose_name='Nombre de curso')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.status', verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nombre de usuario')),
            ],
            options={
                'verbose_name': 'Curso de usuario',
                'verbose_name_plural': 'Cursos de usuarios',
                'ordering': ['-created'],
            },
        ),
    ]
