# Generated by Django 2.1.15 on 2021-01-15 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20201203_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercertificates',
            name='course',
        ),
        migrations.RemoveField(
            model_name='usercertificates',
            name='status',
        ),
        migrations.RemoveField(
            model_name='usercertificates',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='certificates',
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.ContentHeader', verbose_name='Nombre de curso'),
        ),
        migrations.DeleteModel(
            name='UserCertificates',
        ),
    ]
