# Generated by Django 2.1.15 on 2021-01-27 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0004_usergrades'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0011_contentmedia_genially'),
        ('status', '0001_initial'),
        ('user_profile', '0005_auto_20210121_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityGrades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comentario')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.ActivityUsers', verbose_name='Actividad')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.ContentHeader', verbose_name='Curso')),
                ('grade', models.ForeignKey(default='NA', on_delete=django.db.models.deletion.CASCADE, to='catalogues.UserGrades', verbose_name='Calificacion')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.Status', verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Calificaciones de usuario',
                'verbose_name_plural': 'Calificaciones de usuarios',
            },
        ),
    ]
