# Generated by Django 2.1.15 on 2021-01-28 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_activitygrades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitygrades',
            name='status',
        ),
    ]
