# Generated by Django 2.1.15 on 2021-01-28 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_remove_activitygrades_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='status.StatusUserCourse', verbose_name='Status'),
        ),
    ]
