# Generated by Django 2.1.15 on 2021-02-01 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_usergradestatus'),
        ('courses', '0017_ansusertest_question'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0008_auto_20210128_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourseGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calf', models.CharField(max_length=254, verbose_name='Calificacion')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.ContentHeader', verbose_name='Curso')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.UserGradeStatus', verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Calificaciones de curso',
                'verbose_name_plural': 'Calificaciones de cursos',
            },
        ),
    ]
