# Generated by Django 2.1.15 on 2021-02-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_auto_20210202_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercertificates',
            name='cert_file',
            field=models.CharField(max_length=254, verbose_name='Certificado'),
        ),
    ]
