# Generated by Django 2.1.15 on 2021-02-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_statussubscribecourse_statususercourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGradeStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Course grade Status',
                'verbose_name_plural': 'Course grade Status',
            },
        ),
    ]
